[runtime.dev]
target = "qemux86-64"

[runtime.dev.dependencies]
avocado-img-bootfiles = "*"
avocado-img-rootfs = "*"
avocado-img-initramfs = "*"
avocado-dev = {ext = "avocado-dev"}
peridio = {ext = "peridio"}

[sdk]
image = "avocadolinux/sdk:apollo-edge"

[sdk.dependencies]
nativesdk-qemu-system-x86-64 = "*"

[ext.avocado-dev]
types = ["sysext", "confext"]
scopes = ["system"]
overlay = "overlays/avocado-dev"
modprobe = ["nfs"]
enable_services = ["sshd.socket"]

[ext.avocado-dev.users.root]
password = ""

[ext.avocado-dev.users.avocado]
groups = ["avocado"]
password = "$6$9YieAo4LtYEIqB6K$og/ykbnIiXP21yc6WHAVKkkIMNE5jaho8Ijj6zFo0UlOxWGpH9xrduFc0P9UYBtQXz2LrJjx7DK7/XAObLoqh0"

[ext.avocado-dev.groups.avocado]
gid = 1000

[ext.avocado-dev.dependencies]
avocado-hitl = "*"
openssh = "*"

[ext.avocado-dev.sdk.dependencies]
nativesdk-avocado-hitl = "*"

[ext.peridio]
types = ["sysext", "confext"]
enable_services = ["peridiod.service"]
# overlay = {dir = "peridiod-overlay", mode = "opaque"}
overlay = "overlays/peridio"

[ext.peridio.dependencies]
peridiod = "*"
